# src/BaseBundle/Resources/config/doctrine/Contact.orm.yml
BaseBundle\Entity\Contact:
    type: entity
    table: contact
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 100
        first_name:
            type: string
            length: 100
        mail:
            type: string
            length: 100
        subject:
            type: string
            length: 100
        sousMotif:
            type: string
            length: 100
        request:
            type: text