base_session:
    resource: "@BaseBundle/Resources/config/routing/session.yml"
    prefix:   /session

base_question:
        resource: "@BaseBundle/Resources/config/routing/question.yml"
        prefix:   /question

base_theme:
        resource: "@BaseBundle/Resources/config/routing/theme.yml"
        prefix:   /theme

base_homepage:
    path:     /
    defaults: { _controller: BaseBundle:HomePage:homePage } #HomePage = nom de la classe du controller, homePage = nom de l'action ds le controller (on ne riens pas compte des suffixe)

base_myAccount:
    path:     /myAccount
    defaults: { _controller: BaseBundle:MyAccount:myAccount }

base_register:
    path:     /register
    defaults: { _controller: BaseBundle:Register:Register }

base_ajax_add_checkbox_superAdmin:
    path:  /ajax
    defaults: { _controller: BaseBundle:Ajax:add_checkbox_superAdmin }

base_confirm_email:
    path: /confirm/{token}
    defaults: { _controller: BaseBundle:Register:Confirm }

base_contact:
    path:      /contact
    defaults:  { _controller: BaseBundle:Contact:contact }

base_ajax_contact_subjects:
    path:  /ajaxContactSubjects
    defaults: { _controller: BaseBundle:Ajax:get_subjects }
